version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      huaweicloud:
        patterns: ["github.com/huaweicloud/*"]
      k8s:
        patterns: ["k8s.io/*", "sigs.k8s.io/*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
